version: 2

jobs:
  build:
    machine:
      timezone:
        Asia/Tokyo
    branches:
      - master
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "01:2a:8f:4c:b0:e7:68:e5:57:b2:06:88:77:7f:50:cf"
      - deploy:
          command: rsync -auz ./html/ ${REMOTE_USER}@${DEST}:/home/www
